name: fileactions

services:
  web-server:
    build:
      context: ./php
      target: prod
    restart: unless-stopped
    volumes:
      - ..:/var/www/site:z
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf:z
    ports:
      - "127.0.0.1:40055:80"
