version: "3.7"
services:
  web-server:
    build:
      context: ./php
    image: localhost/php-web-server:latest
    restart: always
    volumes:
      - ..:/var/www/site:z
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf:z
      - ./php/php.ini:/usr/local/etc/php/php.ini:z
    ports:
      - "8080:80"
