parameters:
    env(APP_SECRET): ''
    env(VAR_DUMPER_SERVER): '127.0.0.1:9912'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\EventSubscriber\LocaleSubscriber:
        arguments:
            $defaultLocale: '%kernel.default_locale%'

    App\Service\FileServiceInterface: '@App\Service\FileService'
